### ISSUE TITLE
Controls option

### ISSUE THREAD

**Issue by vishalkr058** [cycjimmy/react-jsmpeg-player-demo#10]
I am using this player in my react application which has many components including live video streaming, but i want to use controls like play/pause, skipping, volume control in the player window (Not like play, pause, stop button as given in the demo), so how can i use control options in a player?

**Comment by vishalkr058** [comment]
@cycjimmy if u could help me on this?

**Comment by cycjimmy** [comment]
You can put your own user interface control buttons in the player window.
